/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "AlphaBuilder",
  "tagline": "Quant Research Project",
  "favicon": "img/favicon_1.png",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://alphabuilder.xyz",
  "baseUrl": "/",
  "organizationName": "Jeetmu",
  "projectName": "AlphaBuilder-Site",
  "trailingSlash": false,
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "deploymentBranch": "gh-pages",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": false,
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/homebrew/Documents/AB-S/AlphaBuilder-System/alphabuilder_site/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexDocs": false,
        "indexBlog": false,
        "indexPages": true,
        "searchBarPosition": "right",
        "searchBarShortcut": false,
        "searchResultLimits": 4
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "style": "dark",
      "logo": {
        "alt": "AlphaBuilder Logo",
        "src": "/img/Logo_4.svg",
        "style": {
          "margin": 0,
          "padding": 0
        }
      },
      "items": [
        {
          "type": "dropdown",
          "to": "/signals",
          "label": "Signals",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/signals/rule_based_signals",
              "label": "Rule Based Signals"
            },
            {
              "to": "/signals/formulaic_alphas",
              "label": "Formulaic Alphas"
            },
            {
              "to": "/signals/regime_weighted_aware_signals",
              "label": "Regime Weighted Aware Signals"
            },
            {
              "to": "/signals/volatility_garch_signals",
              "label": "Volatility / GARCH Signals"
            },
            {
              "to": "/signals/statistical_arb_signals",
              "label": "Statistical / Arb Signals"
            },
            {
              "to": "/signals/network_aware_signals",
              "label": "Network-Aware Signals"
            },
            {
              "to": "/signals/bayesian_probabilistic_signals",
              "label": "Bayseian / Probabilistic Signals"
            },
            {
              "to": "/signals/entropy_based_signals",
              "label": "Entropy-Based Signals"
            },
            {
              "to": "/signals/fractal_based_signals",
              "label": "Fractal-Based Signals"
            },
            {
              "to": "/signals/event_sentiment_signals",
              "label": "Event / Sentiment Signals "
            },
            {
              "to": "/signals/multi_resolution_signals",
              "label": "Multi-Resolution Signals"
            },
            {
              "to": "/signals/derived_meta_signals",
              "label": "Derived / Meta Signals"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/risk",
          "label": "Risk",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/risk/basic_statistical_risk",
              "label": "Basic Statistical Risk"
            },
            {
              "to": "/risk/distribution_based_risk",
              "label": "Distribution-Based Risk"
            },
            {
              "to": "/risk/volatility_modelling",
              "label": "Volatility Modeling"
            },
            {
              "to": "/risk/multi_asset_cross_asset_volatility",
              "label": "Multi-Asset / Cross-Asset Volatility"
            },
            {
              "to": "/risk/regime_aware_risk",
              "label": "Regime-Aware Risk"
            },
            {
              "to": "/risk/scenario_stress_testing",
              "label": "Scenario & Stress Testing"
            },
            {
              "to": "/risk/correlation_network_risk",
              "label": "Correlation & Network Risk"
            },
            {
              "to": "/risk/signal_to_risk_mapping",
              "label": "Signal-to-Risk Mapping"
            },
            {
              "to": "/risk/bayesian_probabilistic_risk",
              "label": "Bayesian / Probabilistic Risk"
            },
            {
              "to": "/risk/entropy_based_risk",
              "label": "Entropy-Based Risk"
            },
            {
              "to": "/risk/rl_dynamic_risk_control",
              "label": "RL-Based Dynamic Risk Control"
            },
            {
              "to": "/risk/factor_exposure_constraints",
              "label": "Factor / Exposure Constraints"
            },
            {
              "to": "/risk/tail_extreme_event_risk",
              "label": "Tail / Extreme Event Risk"
            },
            {
              "to": "/risk/rolling_multi_horizon_risk",
              "label": "Rolling / Multi-Horizon Risk"
            },
            {
              "to": "/risk/derived_hybrid_risk_signals",
              "label": "Derived / Hybrid Risk Signals"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/optimizer",
          "label": "Optimizer",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/optimizer/classical_portfolio_optimization",
              "label": "Classical Portfolio Optimization"
            },
            {
              "to": "/optimizer/risk_adjusted_optimization",
              "label": "Risk-Adjusted Optimization"
            },
            {
              "to": "/optimizer/factor_exposure_constraints",
              "label": "Factor / Exposure Constraints"
            },
            {
              "to": "/optimizer/heuristic_optimization",
              "label": "Heuristic Optimization"
            },
            {
              "to": "/optimizer/non_convex_optimization",
              "label": "Non-Convex Optimization"
            },
            {
              "to": "/optimizer/multi_objective_pareto_optimization",
              "label": "Multi-Objective / Pareto Optimization"
            },
            {
              "to": "/optimizer/regime_aware_optimization",
              "label": "Regime-Aware Optimization"
            },
            {
              "to": "/optimizer/rl_based_portfolio_optimization",
              "label": "RL-Based Portfolio Optimization"
            },
            {
              "to": "/optimizer/scenario_stress_aware_optimization",
              "label": "Scenario / Stress-Aware Optimization"
            },
            {
              "to": "/optimizer/meta_learning_cross_asset_adaptation",
              "label": "Meta-Learning / Cross-Asset Adaptation"
            },
            {
              "to": "/optimizer/multi_horizon_optimization",
              "label": "Multi-Horizon Optimization"
            },
            {
              "to": "/optimizer/hybrid_ensemble_optimization",
              "label": "Hybrid / Ensemble Optimization"
            },
            {
              "to": "/optimizer/entropy_based_allocation",
              "label": "Entropy-Based Allocation"
            },
            {
              "to": "/optimizer/diversification_based_allocation",
              "label": "Diversification-Based Allocation"
            },
            {
              "to": "/optimizer/derived_composite_objectives",
              "label": "Derived / Composite Objectives"
            },
            {
              "to": "/optimizer/network_aware_optimization",
              "label": "Network Aware Optimization"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/backtest",
          "label": "Backtest",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/backtest/backtest_pipeline",
              "label": "Backtest Pipeline"
            },
            {
              "to": "/backtest/performance_metrics",
              "label": "Performance Metrics"
            },
            {
              "to": "/backtest/transaction_costs_slippage",
              "label": "Transaction Costs & Slippage"
            },
            {
              "to": "/backtest/turnover_rebalancing",
              "label": "Turnover & Rebalancing"
            },
            {
              "to": "/backtest/regime_wise_evaluation",
              "label": "Regime-Wise Evaluation"
            },
            {
              "to": "/backtest/risk_constraint_validation",
              "label": "Risk & Constraint Validation"
            },
            {
              "to": "/backtest/signal_attribution",
              "label": "Signal Attribution"
            },
            {
              "to": "/backtest/portfolio_diagnostics",
              "label": "Portfolio Diagnostics"
            },
            {
              "to": "/backtest/stress_backtesting",
              "label": "Stress & Scenario Backtesting"
            },
            {
              "to": "/backtest/out_of_sample_testing",
              "label": "Out-of-Sample & Walk-Forward"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/research",
          "label": "Research",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/research/working_papers",
              "label": "Working Papers"
            },
            {
              "to": "/research/collaborative_research",
              "label": "Collaborative Research"
            },
            {
              "to": "/research/peer_reviewed",
              "label": "Peer-Reviewed"
            },
            {
              "to": "/research/preprints_notes",
              "label": "Preprints & Notes"
            },
            {
              "to": "/research/reproducibility",
              "label": "Reproducibility & Code"
            }
          ]
        },
        {
          "type": "dropdown",
          "to": "/community/contact",
          "label": "Community",
          "position": "left",
          "className": "center-navbar",
          "items": [
            {
              "to": "/community/blog",
              "label": "Blogs"
            },
            {
              "to": "/community/learn_more",
              "label": "Learn More"
            },
            {
              "to": "/community/status",
              "label": "Status"
            },
            {
              "to": "/community/about",
              "label": "About"
            },
            {
              "to": "/community/contact",
              "label": "Contact"
            },
            {
              "href": "https://discord.gg/rz6wPGYQBH",
              "label": "Discord",
              "target": "_blank"
            }
          ]
        },
        {
          "href": "https://app.alphabuilder.xyz/",
          "label": "Launch App",
          "position": "left",
          "className": "center-navbar navbar__item--launch-app"
        }
      ],
      "hideOnScroll": false
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
